//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BZY.OA.WebService.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.StudyWebServiceSoap")]
    public interface StudyWebServiceSoap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 HelloWorldResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        BZY.OA.WebService.ServiceReference1.HelloWorldResponse HelloWorld(BZY.OA.WebService.ServiceReference1.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<BZY.OA.WebService.ServiceReference1.HelloWorldResponse> HelloWorldAsync(BZY.OA.WebService.ServiceReference1.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add", ReplyAction="*")]
        int Add(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add", ReplyAction="*")]
        System.Threading.Tasks.Task<int> AddAsync(int a, int b);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 LoadUserInfoListResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LoadUserInfoList", ReplyAction="*")]
        BZY.OA.WebService.ServiceReference1.LoadUserInfoListResponse LoadUserInfoList(BZY.OA.WebService.ServiceReference1.LoadUserInfoListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LoadUserInfoList", ReplyAction="*")]
        System.Threading.Tasks.Task<BZY.OA.WebService.ServiceReference1.LoadUserInfoListResponse> LoadUserInfoListAsync(BZY.OA.WebService.ServiceReference1.LoadUserInfoListRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public BZY.OA.WebService.ServiceReference1.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(BZY.OA.WebService.ServiceReference1.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public BZY.OA.WebService.ServiceReference1.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(BZY.OA.WebService.ServiceReference1.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoadUserInfoListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoadUserInfoList", Namespace="http://tempuri.org/", Order=0)]
        public BZY.OA.WebService.ServiceReference1.LoadUserInfoListRequestBody Body;
        
        public LoadUserInfoListRequest() {
        }
        
        public LoadUserInfoListRequest(BZY.OA.WebService.ServiceReference1.LoadUserInfoListRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class LoadUserInfoListRequestBody {
        
        public LoadUserInfoListRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoadUserInfoListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoadUserInfoListResponse", Namespace="http://tempuri.org/", Order=0)]
        public BZY.OA.WebService.ServiceReference1.LoadUserInfoListResponseBody Body;
        
        public LoadUserInfoListResponse() {
        }
        
        public LoadUserInfoListResponse(BZY.OA.WebService.ServiceReference1.LoadUserInfoListResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoadUserInfoListResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string LoadUserInfoListResult;
        
        public LoadUserInfoListResponseBody() {
        }
        
        public LoadUserInfoListResponseBody(string LoadUserInfoListResult) {
            this.LoadUserInfoListResult = LoadUserInfoListResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface StudyWebServiceSoapChannel : BZY.OA.WebService.ServiceReference1.StudyWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StudyWebServiceSoapClient : System.ServiceModel.ClientBase<BZY.OA.WebService.ServiceReference1.StudyWebServiceSoap>, BZY.OA.WebService.ServiceReference1.StudyWebServiceSoap {
        
        public StudyWebServiceSoapClient() {
        }
        
        public StudyWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StudyWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StudyWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StudyWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BZY.OA.WebService.ServiceReference1.HelloWorldResponse BZY.OA.WebService.ServiceReference1.StudyWebServiceSoap.HelloWorld(BZY.OA.WebService.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            BZY.OA.WebService.ServiceReference1.HelloWorldRequest inValue = new BZY.OA.WebService.ServiceReference1.HelloWorldRequest();
            inValue.Body = new BZY.OA.WebService.ServiceReference1.HelloWorldRequestBody();
            BZY.OA.WebService.ServiceReference1.HelloWorldResponse retVal = ((BZY.OA.WebService.ServiceReference1.StudyWebServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BZY.OA.WebService.ServiceReference1.HelloWorldResponse> BZY.OA.WebService.ServiceReference1.StudyWebServiceSoap.HelloWorldAsync(BZY.OA.WebService.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<BZY.OA.WebService.ServiceReference1.HelloWorldResponse> HelloWorldAsync() {
            BZY.OA.WebService.ServiceReference1.HelloWorldRequest inValue = new BZY.OA.WebService.ServiceReference1.HelloWorldRequest();
            inValue.Body = new BZY.OA.WebService.ServiceReference1.HelloWorldRequestBody();
            return ((BZY.OA.WebService.ServiceReference1.StudyWebServiceSoap)(this)).HelloWorldAsync(inValue);
        }
        
        public int Add(int a, int b) {
            return base.Channel.Add(a, b);
        }
        
        public System.Threading.Tasks.Task<int> AddAsync(int a, int b) {
            return base.Channel.AddAsync(a, b);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BZY.OA.WebService.ServiceReference1.LoadUserInfoListResponse BZY.OA.WebService.ServiceReference1.StudyWebServiceSoap.LoadUserInfoList(BZY.OA.WebService.ServiceReference1.LoadUserInfoListRequest request) {
            return base.Channel.LoadUserInfoList(request);
        }
        
        public string LoadUserInfoList() {
            BZY.OA.WebService.ServiceReference1.LoadUserInfoListRequest inValue = new BZY.OA.WebService.ServiceReference1.LoadUserInfoListRequest();
            inValue.Body = new BZY.OA.WebService.ServiceReference1.LoadUserInfoListRequestBody();
            BZY.OA.WebService.ServiceReference1.LoadUserInfoListResponse retVal = ((BZY.OA.WebService.ServiceReference1.StudyWebServiceSoap)(this)).LoadUserInfoList(inValue);
            return retVal.Body.LoadUserInfoListResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BZY.OA.WebService.ServiceReference1.LoadUserInfoListResponse> BZY.OA.WebService.ServiceReference1.StudyWebServiceSoap.LoadUserInfoListAsync(BZY.OA.WebService.ServiceReference1.LoadUserInfoListRequest request) {
            return base.Channel.LoadUserInfoListAsync(request);
        }
        
        public System.Threading.Tasks.Task<BZY.OA.WebService.ServiceReference1.LoadUserInfoListResponse> LoadUserInfoListAsync() {
            BZY.OA.WebService.ServiceReference1.LoadUserInfoListRequest inValue = new BZY.OA.WebService.ServiceReference1.LoadUserInfoListRequest();
            inValue.Body = new BZY.OA.WebService.ServiceReference1.LoadUserInfoListRequestBody();
            return ((BZY.OA.WebService.ServiceReference1.StudyWebServiceSoap)(this)).LoadUserInfoListAsync(inValue);
        }
    }
}
